apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vestigia-ingress
spec:
  rules:
  - host: vestigia.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vestigia-api
            port:
              number: 80
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: vestigia-dashboard
            port:
              number: 8501
