# Auto-generated by setup_environment.py
# DO NOT EDIT - Regenerate with: python setup_environment.py --mode development

from config import VestigiaConfig, VestigiaMode

# Global config instance
CONFIG = VestigiaConfig(mode=VestigiaMode.DEVELOPMENT)

# Quick access
MODE = CONFIG.mode
LEDGER_PATH = CONFIG.ledger_path
WITNESS_PATH = CONFIG.witness_path
ENABLE_HARDENING = CONFIG.enable_hardening
