#!/usr/bin/env python3
"""
Vestigia Environment Setup
Automatically configures dev/staging/production modes

Run: python setup_environment.py --mode development
"""

import os
import sys
import argparse
from pathlib import Path
import subprocess


class EnvironmentSetup:
    """Setup Vestigia for different environments"""
    
    def __init__(self, mode: str):
        self.mode = mode.lower()
        self.base_dir = Path.cwd()
    
    def create_env_file(self):
        """Create .env file with mode-specific settings"""
        env_content = f"""# Vestigia Environment Configuration
# Mode: {self.mode.upper()}

VESTIGIA_MODE={self.mode}
"""
        
        # Generate secret salt
        import secrets
        secret = secrets.token_urlsafe(32)
        env_content += f"VESTIGIA_SECRET_SALT={secret}\n"
        
        # Mode-specific settings
        if self.mode == 'development':
            env_content += """
# Development settings
VESTIGIA_ENABLE_HARDENING=false
VESTIGIA_VERBOSE=true
VESTIGIA_EXTERNAL_WITNESS=false
"""
        elif self.mode == 'staging':
            env_content += """
# Staging settings
VESTIGIA_ENABLE_HARDENING=true
VESTIGIA_VERBOSE=true
VESTIGIA_EXTERNAL_WITNESS=false
"""
        else:  # production
            env_content += """
# Production settings
VESTIGIA_ENABLE_HARDENING=true
VESTIGIA_VERBOSE=false
VESTIGIA_EXTERNAL_WITNESS=true
VESTIGIA_EXTERNAL_WITNESS_URL=https://witness.company.com/api/anchor
"""
        
        # Write .env
        env_path = self.base_dir / '.env'
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created .env file for {self.mode.upper()} mode")
    
    def create_directories(self):
        """Create mode-specific directories"""
        if self.mode == 'production':
            dirs = [
                '/var/log/vestigia',
                self.base_dir / 'backups',
                self.base_dir / 'compliance_exports'
            ]
        elif self.mode == 'staging':
            dirs = [
                self.base_dir / 'staging',
                self.base_dir / 'staging/history',
                self.base_dir / 'backups'
            ]
        else:  # development
            dirs = [
                self.base_dir / 'data',
                self.base_dir / 'data/history',
                self.base_dir / 'backups'
            ]
        
        for dir_path in dirs:
            try:
                Path(dir_path).mkdir(parents=True, exist_ok=True)
                print(f"✅ Created directory: {dir_path}")
            except PermissionError:
                print(f"⚠️  Permission denied: {dir_path} (may need sudo)")
    
    def setup_hardening(self):
        """Configure file permissions based on mode"""
        if self.mode == 'development':
            print("⚠️  Development mode - hardening disabled")
            print("   Files remain writable for testing")
            return
        
        print(f"🔒 Configuring {self.mode} hardening...")
        
        # Remove any existing hardening
        subprocess.run(['python', 'hardening.py', '--disable'], 
                      capture_output=True)
        
        # Apply mode-appropriate hardening
        if self.mode == 'staging':
            # Staging: Read-only but not immutable
            subprocess.run(['python', 'hardening.py', '--readonly'])
            print("   ✅ Staging: Read-only mode enabled")
        
        elif self.mode == 'production':
            # Production: Full hardening
            result = subprocess.run(
                ['sudo', 'python', 'hardening.py', '--enable', '--backup'],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                print("   ✅ Production: Full hardening enabled")
                print("   ⚠️  Files are now append-only/immutable")
            else:
                print("   ⚠️  Hardening failed (may need sudo)")
    
    def create_config_file(self):
        """Create Python config import"""
        config_py = f"""# Auto-generated by setup_environment.py
# DO NOT EDIT - Regenerate with: python setup_environment.py --mode {self.mode}

from config import VestigiaConfig, VestigiaMode

# Global config instance
CONFIG = VestigiaConfig(mode=VestigiaMode.{self.mode.upper()})

# Quick access
MODE = CONFIG.mode
LEDGER_PATH = CONFIG.ledger_path
WITNESS_PATH = CONFIG.witness_path
ENABLE_HARDENING = CONFIG.enable_hardening
"""
        
        with open(self.base_dir / 'env_config.py', 'w') as f:
            f.write(config_py)
        
        print(f"✅ Created env_config.py")
    
    def print_summary(self):
        """Print setup summary"""
        print("\n" + "=" * 70)
        print(f"  ✅ Vestigia {self.mode.upper()} Environment Ready")
        print("=" * 70 + "\n")
        
        print("Configuration:")
        print(f"  Mode: {self.mode.upper()}")
        print(f"  .env file: Created")
        print(f"  Directories: Created")
        
        if self.mode == 'development':
            print(f"  Hardening: ⚠️  DISABLED (files writable)")
        elif self.mode == 'staging':
            print(f"  Hardening: 🔒 Read-only")
        else:
            print(f"  Hardening: 🔒 Append-only + Immutable")
        
        print("\nQuick Start:")
        print(f"  1. source venv/bin/activate")
        print(f"  2. python cli.py log agent_001 TOOL_EXECUTION SUCCESS 'Test'")
        print(f"  3. python cli.py verify")
        
        if self.mode == 'development':
            print(f"\n💡 Dev Mode Tips:")
            print(f"  • Files remain writable for easy testing")
            print(f"  • Verbose logging enabled")
            print(f"  • No hardening applied")
            print(f"  • Switch to staging: python setup_environment.py --mode staging")
        elif self.mode == 'production':
            print(f"\n⚠️  Production Mode Notes:")
            print(f"  • Files are append-only (can't modify/delete)")
            print(f"  • To add events: python cli.py log ...")
            print(f"  • For maintenance: sudo python hardening.py --disable")
            print(f"  • External witness required (configure in .env)")
        
        print("\n" + "=" * 70)


def main():
    parser = argparse.ArgumentParser(
        description="Setup Vestigia environment"
    )
    parser.add_argument(
        '--mode',
        choices=['development', 'staging', 'production'],
        default='development',
        help='Environment mode'
    )
    
    args = parser.parse_args()
    
    print("\n" + "=" * 70)
    print(f"  🗃️  Vestigia Environment Setup")
    print("=" * 70 + "\n")
    
    setup = EnvironmentSetup(args.mode)
    
    try:
        setup.create_directories()
        setup.create_env_file()
        setup.create_config_file()
        setup.setup_hardening()
        setup.print_summary()
        
        return 0
    
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
