apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tessera-ingress
spec:
  rules:
    - host: tessera.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tessera-api
                port:
                  number: 80
