#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "🌐 Starting VerityFlux 2.0 Web Interface Demo"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Starting Streamlit UI..."
echo "Access at: http://localhost:8503"
echo ""
echo "📋 Demo Steps:"
echo "   1. Select 'Security Scan' mode"
echo "   2. Provider: ollama"
echo "   3. Model: tinyllama"
echo "   4. Check 'Is Agent?' if testing agent features"
echo "   5. Click 'Run Scan'"
echo ""
echo "For Cognitive Firewall:"
echo "   1. Select 'Cognitive Firewall' mode"
echo "   2. Try the goal hijacking example"
echo "   3. Tool: delete_database"
echo "   4. Goal: Optimize database performance"
echo ""
echo "Starting server..."
streamlit run web_ui.py
